#!/bin/bash

case $# in
    0) inf=~/.config/midori/bookmarks.db ;;
    1) inf="$@" ;;
    *) echo "usage: $0 [bookmarks.db] > bookmarks.html\ninput defaults to ~/.config/midori/bookmarks.db"; exit 0 ;;
esac

midori-bookmarks-to-tsv | awk -F'	' 'function escapeName(name) { gsub(/&/, "\\&amp;", name); gsub(/</, "\\&lt;", name); gsub(/>/, "\\&gt;", name); return name; } function escapeUrl(url) { url = escapeName(url); gsub(/"/, "\\&#39;", url); return url; } BEGIN { printf "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>Midori Bookmarks Dump %s</title></head><body><ul>\n", strftime("%FT%T%z", systime()) } { printf "<li><p>%s : <a href=\"%s\">%s</a></p></li>\n", $1, escapeUrl($2), escapeName($3) } END { print "</ul></body></html>" }'
